[package]
authors = ["qians <qiangezaici@outlook.com>"]
edition = "2021"
name = "im-infra-link"
version = "1.0.0"

[[bin]]
name = "im-infra-link"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
axum = { version = "0.6", features = ["ws", "headers", "macros"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.7"
time = "0.3"
md-5 = "0.10"
ahash = "0.8"
openraft = "0.8"
once_cell = { version = "1", default-features = false }
rskafka = { version = "0.3", path = "../rskafka" }
fred = { version = "6.0.0", features = ["tokio-rustls"] }

[dev-dependencies]
once_cell = "1"
